# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=100)),
                ('pack', models.CharField(max_length=80)),
                ('website', models.CharField(max_length=80)),
                ('facebookpage', models.CharField(max_length=80)),
                ('responsable', models.CharField(max_length=80)),
            ],
        ),
    ]
